# set JEKYLL_ENV=production | bundle exec jekyll build
title: Asesoría Financiera CG
email: email@asesoriafinancieracg.com
description: >- # this means to ignore newlines until "baseurl:"
  Asesoría Financiera especializada en temas de Bienes Raices, Patrimonial
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://asesoriafinancieracg.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap